INSERT INTO assets (asset_id, asset_code, asset_type, asset_name, decimals)
VALUES ('XLM', 'XLM', 'classic', 'Stellar Lumens', 7)
ON CONFLICT (asset_id) DO NOTHING;

INSERT INTO assets (asset_id, asset_code, asset_type, issuer_address, asset_name, decimals)
VALUES 
    ('USDC:GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335XPB7X3NCYGS3YNRM64K6L5O3', 'USDC', 'classic', 'GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335XPB7X3NCYGS3YNRM64K6L5O3', 'USD Coin', 7),
    ('yXLM:GARDNV3Q7YSTZZYUTYTPSTZ4YDSST6SCSHLZMT6SCSHLZMT6SCSHLZMT', 'yXLM', 'classic', 'GARDNV3Q7YSTZZYUTYTPSTZ4YDSST6SCSHLZMT6SCSHLZMT6SCSHLZMT', 'Yield XLM', 7)
ON CONFLICT (asset_id) DO NOTHING;