package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"

	"github.com/celerfi/stellar-indexer-go/graph/model"
	"github.com/celerfi/stellar-indexer-go/utils"
)

// Stellar is the resolver for the stellar field.
func (r *queryResolver) Stellar(ctx context.Context) (*model.Stellar, error) {
	return &model.Stellar{}, nil
}

// Transaction is the resolver for the transaction field.
func (r *stellarResolver) Transaction(ctx context.Context, obj *model.Stellar, hash string) (*model.Transaction, error) {
	tx, err := utils.GetTransactionByHash(hash)
	if err != nil {
		return nil, err
	}
	return &model.Transaction{
		BlockTime:       tx.BlockTime,
		TransactionHash: tx.TransactionHash,
		LedgerSequence:  int32(tx.LedgerSequence),
		DexName:         &tx.DexName,
		TokenIn:         &tx.TokenIn,
		TokenOut:        &tx.TokenOut,
		AmountBought:    &tx.AmountBought,
		AmountSold:      &tx.AmountSold,
		Status:          &tx.Status,
	}, nil
}

// Transactions is the resolver for the transactions field.
func (r *stellarResolver) Transactions(ctx context.Context, obj *model.Stellar, limit *int32, offset *int32) ([]*model.Transaction, error) {
	l, o := 20, 0
	if limit != nil {
		l = int(*limit)
	}
	if offset != nil {
		o = int(*offset)
	}
	txs, err := utils.GetTransactions(l, o)
	if err != nil {
		return nil, err
	}
	var results []*model.Transaction
	for _, tx := range txs {
		txCopy := tx // avoid closure issues
		results = append(results, &model.Transaction{
			BlockTime:       txCopy.BlockTime,
			TransactionHash: txCopy.TransactionHash,
			LedgerSequence:  int32(txCopy.LedgerSequence),
			DexName:         &txCopy.DexName,
			TokenIn:         &txCopy.TokenIn,
			TokenOut:        &txCopy.TokenOut,
			AmountBought:    &txCopy.AmountBought,
			AmountSold:      &txCopy.AmountSold,
			Status:          &txCopy.Status,
		})
	}
	return results, nil
}

// Token is the resolver for the token field.
func (r *stellarResolver) Token(ctx context.Context, obj *model.Stellar, address string) (*model.Token, error) {
	t, err := utils.GetTokenByAddress(address)
	if err != nil {
		return nil, err
	}
	return &model.Token{
		ContractAddress: t.ContractAddress,
		Symbol:          t.Symbol,
		Name:            t.Name,
		Decimals:        int32(t.Decimals),
		TotalSupply:     t.TotalSupply,
		IsSac:           t.IsSAC,
	}, nil
}

// Tokens is the resolver for the tokens field.
func (r *stellarResolver) Tokens(ctx context.Context, obj *model.Stellar, limit *int32, offset *int32) ([]*model.Token, error) {
	l, o := 20, 0
	if limit != nil {
		l = int(*limit)
	}
	if offset != nil {
		o = int(*offset)
	}
	tokens, err := utils.GetTokens(l, o)
	if err != nil {
		return nil, err
	}
	var results []*model.Token
	for _, t := range tokens {
		tCopy := t
		results = append(results, &model.Token{
			ContractAddress: tCopy.ContractAddress,
			Symbol:          tCopy.Symbol,
			Name:            tCopy.Name,
			Decimals:        int32(tCopy.Decimals),
			TotalSupply:     tCopy.TotalSupply,
			IsSac:           tCopy.IsSAC,
		})
	}
	return results, nil
}

// Pool is the resolver for the pool field.
func (r *stellarResolver) Pool(ctx context.Context, obj *model.Stellar, address string) (*model.Pool, error) {
	p, err := utils.GetPoolByAddress(address)
	if err != nil {
		return nil, err
	}
	return &model.Pool{
		PoolAddress: p["poolAddress"].(string),
		TokenA:      p["tokenA"].(string),
		TokenB:      p["tokenB"].(string),
		FeeBps:      utils.Ptr(int32(p["feeBps"].(int32))),
		Type:        utils.Ptr(p["type"].(string)),
		TvlUsd:      utils.Ptr(p["tvlUsd"].(float64)),
		Volume24h:   utils.Ptr(p["volume24h"].(float64)),
	}, nil
}

// Pools is the resolver for the pools field.
func (r *stellarResolver) Pools(ctx context.Context, obj *model.Stellar, limit *int32, offset *int32) ([]*model.Pool, error) {
	l, o := 20, 0
	if limit != nil {
		l = int(*limit)
	}
	if offset != nil {
		o = int(*offset)
	}
	pools, err := utils.GetPools(l, o)
	if err != nil {
		return nil, err
	}
	var results []*model.Pool
	for _, p := range pools {
		results = append(results, &model.Pool{
			PoolAddress: p["poolAddress"].(string),
			TokenA:      p["tokenA"].(string),
			TokenB:      p["tokenB"].(string),
			FeeBps:      utils.Ptr(int32(p["feeBps"].(int32))),
			Type:        utils.Ptr(p["type"].(string)),
			TvlUsd:      utils.Ptr(p["tvlUsd"].(float64)),
			Volume24h:   utils.Ptr(p["volume24h"].(float64)),
		})
	}
	return results, nil
}

// TokenOHLCV is the resolver for the tokenOHLCV field.
func (r *stellarResolver) TokenOHLCV(ctx context.Context, obj *model.Stellar, tokenAddress string, interval string) ([]*model.OHLCVData, error) {
	data, err := utils.GetTokenOHLCV(tokenAddress, interval)
	if err != nil {
		return nil, err
	}
	var results []*model.OHLCVData
	for _, d := range data {
		results = append(results, &model.OHLCVData{
			Bucket:    d["bucket"].(time.Time),
			Open:      utils.Ptr(d["open"].(float64)),
			High:      utils.Ptr(d["high"].(float64)),
			Low:       utils.Ptr(d["low"].(float64)),
			Close:     utils.Ptr(d["close"].(float64)),
			VolumeUsd: utils.Ptr(d["volumeUsd"].(float64)),
		})
	}
	return results, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Stellar returns StellarResolver implementation.
func (r *Resolver) Stellar() StellarResolver { return &stellarResolver{r} }

type queryResolver struct{ *Resolver }
type stellarResolver struct{ *Resolver }
