// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type OHLCVData struct {
	Bucket    time.Time `json:"bucket"`
	Open      *float64  `json:"open,omitempty"`
	High      *float64  `json:"high,omitempty"`
	Low       *float64  `json:"low,omitempty"`
	Close     *float64  `json:"close,omitempty"`
	VolumeUsd *float64  `json:"volumeUsd,omitempty"`
}

type Pool struct {
	PoolAddress string   `json:"poolAddress"`
	TokenA      string   `json:"tokenA"`
	TokenB      string   `json:"tokenB"`
	FeeBps      *int32   `json:"feeBps,omitempty"`
	Type        *string  `json:"type,omitempty"`
	TvlUsd      *float64 `json:"tvlUsd,omitempty"`
	Volume24h   *float64 `json:"volume24h,omitempty"`
}

type Query struct {
}

type Stellar struct {
	Transaction  *Transaction   `json:"transaction,omitempty"`
	Transactions []*Transaction `json:"transactions"`
	Token        *Token         `json:"token,omitempty"`
	Tokens       []*Token       `json:"tokens"`
	Pool         *Pool          `json:"pool,omitempty"`
	Pools        []*Pool        `json:"pools"`
	TokenOhlcv   []*OHLCVData   `json:"tokenOHLCV"`
}

type Token struct {
	ContractAddress string `json:"contractAddress"`
	Symbol          string `json:"symbol"`
	Name            string `json:"name"`
	Decimals        int32  `json:"decimals"`
	TotalSupply     string `json:"totalSupply"`
	IsSac           bool   `json:"isSAC"`
}

type Transaction struct {
	BlockTime       time.Time `json:"blockTime"`
	TransactionHash string    `json:"transactionHash"`
	LedgerSequence  int32     `json:"ledgerSequence"`
	DexName         *string   `json:"dexName,omitempty"`
	TokenIn         *string   `json:"tokenIn,omitempty"`
	TokenOut        *string   `json:"tokenOut,omitempty"`
	AmountBought    *float64  `json:"amountBought,omitempty"`
	AmountSold      *float64  `json:"amountSold,omitempty"`
	Status          *string   `json:"status,omitempty"`
}
