package utils

const (
	DEX_NAME_STELLAR_DEX = "STELLAR-DEX"
	DEX_NAME_AQUARIUS = "aquarius"

	ORDERBOOK_TX_STATUS_MATCHED = "matched"
	ORDERBOOK_TX_STATUS_POSTED = "posted"
	ORDERBOOK_TX_STATUS_PARTIALLY_MATCHED = "partially-matched"

	AQUARIUS_CONTRACT_ID = "CAJXBOGWSRFT7Q7ZKHVTPWGODOBBSPYQVKN2WSMN2WFMPAXX2CETEBAZ"
	LUMENSWAP_CONTRACT_ID = "GAB7STHVD5BDH3EEYXPI3OM7PCS4V443PYB5FNT6CFGJVPDLMKDM24WK"
	SOROSWAP_CONTRACT_ID = "CA4HEQTL2WPEUYKYKCDOHCDNIV4QHNJ7EL4J4NQ6VADP7SYHVRYZ7AW2"
	AQUARIUS_ROUTER_CONTRACT_ID = "CBQDHNBFBZYE4MKPWBSJOPIYLW4SFSXAXUTSXJN76GNKYVYPCKWC6QUK"
	SOROSWAP_ROUTER_CONTRACT_ID = "CAG5LRYQ5JVEUI5TEID72EYOVX44TTUJT5BQR2J6J77FH65PCCFAJDDH"
)
